server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://192.168.56.10:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
      team: Devops
      env: Prod
      component:
  pipeline_stages:
  - logfmt:
      mapping:
        component:
  - labels:
      component:

- job_name: shoehub
  static_configs:
  - targets:
      - localhost
    labels:
      job: shoehub
      app: shoehub
      __path__: /var/log/shoehub/log*

- job_name: python_app_logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: python_app_logs
      app: mypythonapp
      __path__: /var/log/loki_udemy.log
